# Generated by Django 5.1.3 on 2024-12-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=255)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('nomor_telepon', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
