# Generated by Django 5.1.3 on 2024-12-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikasi', '0002_databarang_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databarang',
            name='alamat',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='databarang',
            name='nama_barang',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='databarang',
            name='nomor_telepon',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='databarang',
            name='supplier',
            field=models.CharField(max_length=100),
        ),
    ]
