# Generated by Django 5.1.3 on 2024-12-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikasi', '0003_alter_databarang_alamat_alter_databarang_nama_barang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suplier', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('nomor_telepon', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='DataBarang',
        ),
    ]
