# Generated by Django 5.1.3 on 2024-12-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikasi', '0004_barang_delete_databarang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gudang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100, verbose_name='Nama Barang')),
                ('jumlah_masuk', models.PositiveIntegerField(verbose_name='Jumlah Barang Masuk')),
                ('jumlah_terjual', models.PositiveIntegerField(verbose_name='Jumlah Barang Terjual')),
                ('sisa_barang', models.PositiveIntegerField(verbose_name='Sisa Barang')),
                ('tanggal_update', models.DateField(verbose_name='Tanggal Update')),
            ],
        ),
        migrations.AlterField(
            model_name='barang',
            name='harga',
            field=models.BigIntegerField(),
        ),
    ]
