# Generated by Django 5.1.3 on 2024-12-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikasi', '0005_gudang_alter_barang_harga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gudang',
            old_name='jumlah_masuk',
            new_name='jumlah_barang_masuk',
        ),
        migrations.RenameField(
            model_name='gudang',
            old_name='jumlah_terjual',
            new_name='jumlah_barang_terjual',
        ),
    ]
