# Generated by Django 5.1.3 on 2024-12-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikasi', '0006_rename_jumlah_masuk_gudang_jumlah_barang_masuk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kasir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100, verbose_name='Nama Barang')),
                ('harga', models.PositiveIntegerField(verbose_name='Harga')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
            ],
        ),
    ]
